// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANkr07p0MyzSgnWjaLJJUoOBQL2vJlaEM',
    appId: '1:618880538435:android:7af6936a044f60a09101f6',
    messagingSenderId: '618880538435',
    projectId: 'shiftlanka-dd973',
    storageBucket: 'shiftlanka-dd973.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7l23qb-bIveT1ZMttEYSUHtCn0H9qm4U',
    appId: '1:618880538435:web:3373567f8415ea2c9101f6',
    messagingSenderId: '618880538435',
    projectId: 'shiftlanka-dd973',
    authDomain: 'shiftlanka-dd973.firebaseapp.com',
    storageBucket: 'shiftlanka-dd973.firebasestorage.app',
    measurementId: 'G-WYP6N0BHZC',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCP-Gq_og-ilM95RnsrFybRG6my88MPFVs',
    appId: '1:618880538435:ios:34b97636a0ef02c89101f6',
    messagingSenderId: '618880538435',
    projectId: 'shiftlanka-dd973',
    storageBucket: 'shiftlanka-dd973.firebasestorage.app',
    iosBundleId: 'com.example.shiftlankaUser',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCP-Gq_og-ilM95RnsrFybRG6my88MPFVs',
    appId: '1:618880538435:ios:cfab453deec690249101f6',
    messagingSenderId: '618880538435',
    projectId: 'shiftlanka-dd973',
    storageBucket: 'shiftlanka-dd973.firebasestorage.app',
    iosBundleId: 'com.shiftlanka.user',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7l23qb-bIveT1ZMttEYSUHtCn0H9qm4U',
    appId: '1:618880538435:web:b36c59bf18d5ca899101f6',
    messagingSenderId: '618880538435',
    projectId: 'shiftlanka-dd973',
    authDomain: 'shiftlanka-dd973.firebaseapp.com',
    storageBucket: 'shiftlanka-dd973.firebasestorage.app',
    measurementId: 'G-7RM7DD7PEG',
  );

}